### ISSUE TITLE
Really nice bot, when is the Camelot DEX coming?

### ISSUE THREAD

**Issue by DeFiMasterd** [Yapote/ARBITRUM-SNIPING-BOT-ARBX#1]
Let me know :)

**Comment by Yapote** [comment]
Very soon thanks for asking

**Comment by ShawnXpro** [comment]
Yapote, How may i cantact to you?

**Comment by ShawnXpro** [comment]
> Very soon thanks for asking

May i cantact to you? Would you please share your TG id?

**Comment by Yapote** [comment]
> > Very soon thanks for asking
> 
> May i cantact to you? Would you please share your Telegram id?

kotorkauwn_f@proton.me write me an email

**Comment by Yapote** [comment]
Launching Camelot dex Sniping today
