### ISSUE TITLE
No liquidity 

### ISSUE THREAD

**Issue by dubaigit** [Yapote/ARBITRUM-SNIPING-BOT-ARBX#6]
im getting No liquidity  on every contract i put 
![Screenshot 2023-03-27 012304](https://user-images.githubusercontent.com/20006529/227805404-06537a75-1ac9-4122-b4d0-16dfe767fd85.png)

**Comment by Yapote** [comment]
Do the tokens have BNB liquidity? If not then you need to select BUSD, and if they do, check if the liquidity is on Pancakeswap

**Comment by dubaigit** [comment]
> Do the tokens have BNB liquidity? If not then you need to select BUSD, and if they do, check if the liquidity is on Pancakeswap

its on ARBITRUM i can see my balance and contracts have liquidity

**Comment by Yapote** [comment]
Liquidity on Camelot or Sushiswap?

**Comment by dubaigit** [comment]
Sushiswap

**Comment by Yapote** [comment]
Yes, you need to change "Camelot" to "Sushiswap" in inputs

**Comment by dubaigit** [comment]
That workes thanks
